server:
  port: 9999
  max-http-header-size: 50000
  undertow:
    ioThreads: 15
    workerThreads: 150

management:
  security:
    enabled: false
  health:
    mail:
      enabled: false

auth-server:
  url: http://localhost:9999

spring:
  application:
    name: operationservice
  cloud:
    config:
      enabled: true
      uri: http://localhost:8888
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2kb
      max-file-size: 200MB
      max-request-size: 215MB

#SLF4J
logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO
    com.enrico.microservices: INFO
  file:  /tmp/logs/application.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

check-user-scopes: true
