spring:
  application:
    name: CoffeeShop
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    properties:
      hibernate:
        default_schema: operation
        jdbc:
          lob:
            non_contextual_creation: true
      hbm2ddl:
        auto: update
  database:
    driverClassName: "org.postgresql.Driver"
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/vetstoria?currentSchema=operation
    username: postgres
    password: postgres
    hikari:
      maximumPoolSize: 10
      minimumIdle: 3
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
      leakDetectionThreshold: 15000
  hibernate:
    hbm2ddl: update
  cloud:
    refresh:
      refreshable: none
security:
  oauth2:
    resource:
      userInfoUri: http://localhost:8080/auth/user

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    org:
      hibernate: INFO
      springframework:
        web: INFO
    root: INFO
    com:
      zaxxer:
        hikari: debug
